"""Tests for the Gazebo GUI config generated by gazebo_world.launch.py.

The launch file takes clearpath_gz's stock gui.config, injects the Teleop
topic exactly as clearpath's own gz_sim.launch.py does, and appends a
ResetPose plugin block so the button docks directly below Teleop.
"""
import importlib.util
import os

import pytest

HERE = os.path.dirname(__file__)
_spec = importlib.util.spec_from_file_location(
    'gazebo_world_launch', os.path.join(HERE, '..', 'launch', 'gazebo_world.launch.py'))
gw = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gw)

TEMPLATE = """<?xml version="1.0"?>
<window>
</window>
<plugin filename="MinimalScene" name="3D View">
</plugin>
<plugin filename="Teleop">
    <ignition-gui>
        <property key="state" type="string">docked</property>
    </ignition-gui>
</plugin>
"""

POSE = (-3.0, 2.0, 0.3, 0.0)


def test_teleop_topic_is_injected_once():
    out = gw.build_gui_config(TEMPLATE, '/a200_0000/cmd_vel', 'walls_one_sided',
                              'a200_0000/robot', POSE)
    assert out.count('<plugin filename="Teleop">\n    <topic>/a200_0000/cmd_vel</topic>') == 1
    assert out.count('<topic>') == 1


def test_reset_pose_block_follows_teleop():
    out = gw.build_gui_config(TEMPLATE, '/a200_0000/cmd_vel', 'walls_one_sided',
                              'a200_0000/robot', POSE)
    teleop_at = out.index('<plugin filename="Teleop">')
    reset_at = out.index('<plugin filename="ResetPose"')
    assert reset_at > teleop_at
    # nothing else after it: it must be the last docked plugin so it lands
    # below Teleop in the right-hand dock
    assert out.count('<plugin filename=', reset_at) == 1


def test_reset_pose_block_carries_world_model_and_pose():
    out = gw.build_gui_config(TEMPLATE, '/cmd_vel', 'walls_two_sided', 'robot',
                              (1.5, -2.0, 0.3, 1.5708))
    assert '<world>walls_two_sided</world>' in out
    assert '<model>robot</model>' in out
    assert '<pose>1.5 -2.0 0.3 0 0 1.5708</pose>' in out


def test_missing_teleop_marker_is_an_error():
    with pytest.raises(ValueError):
        gw.build_gui_config('<window></window>\n', '/cmd_vel', 'w', 'robot', POSE)


def test_against_installed_clearpath_config():
    path = '/opt/ros/humble/share/clearpath_gz/config/gui.config'
    if not os.path.isfile(path):
        pytest.skip('clearpath_gz not installed')
    with open(path) as f:
        template = f.read()
    out = gw.build_gui_config(template, '/a200_0000/cmd_vel', 'walls_one_sided',
                              'a200_0000/robot', POSE)
    assert out.startswith('<?xml')
    assert out.rstrip().endswith('</plugin>')
    assert out.index('<plugin filename="ResetPose"') > out.index('<plugin filename="Teleop">')
